src/views/Search.vue

This fixes an issue where search wouldn't trigger when first loading the component. The problem was resolved by adding an initial search term in the created() lifecycle hook.

WOK-361: set initial search term from param in created() hook

---

src/components/nav/menu-component.ts
src/components/search/SearchResults.vue
src/components/search/result-component.ts

So another deep dive into the docs of Vue3 and web components. This is the first draft on how we can do this without the heavy use of observables (when not needed). I have passed the complex search result data as a property, declared it is a property in the web component and then made use of the standard connectedCallback to render the results. This approach seems to work and reduce the "observer load"
Learnings when reading through the docs:
- we should not in (nearly) any case pass complex data as attributes (only simple data). Complex data should be passed as a property and it turns out if your do that _and_ you have declared the property in the web component Vue 3 uses the 'in' operator to check for the presence of DOM properties and prefers to set the value as a DOM property if the …

Move result data from observed attribute to property in web component

---

src/router/index.ts

Locale should now be persisted in URL after first locale switch.
On init we rely on the value stored in localstorage (if any) otherwise we default to 'da'.

Persist locale in url after locale switch

---

src/App.vue
src/api/api-client.ts
src/components/search/Facets.vue
src/components/search/SearchBarWrapper.vue
src/components/search/SearchResults.vue
src/components/search/wc-searchbar.ts
src/store/searchResultStore.ts
src/views/Search.vue

So, this is a little bit of a major overhaul of the way we search. I've reworked it as such:
Everything is now handled by the URL - and a single watcher in the Search.vue file. This was to ensure that we don't fire of searches from other places (ie facets or some other place).
In the search watcher, we look at what has changed - this should be further elaborated to also include the offset / start params when we add the pagination. But the good thing is, thats all we gotta do. Just update the URL and the watcher handles the rest with a new query. (we probably need to add the offset/start to the query aswell, but that shouldn't be too hard)
I've left in some console.logs - I think it's okey they're there for now so we can look at what's going on (if something starts to not work as intended) …

Reworked the way we search

---

src/views/Search.vue

If you go to a fullpost (fx /record/ds.radiotv:oai:du:1819f20a-20e4-44bb-bb9b-5b87e013cb7e), on mobile devices (<800px),  you cannot scroll on the page because of class on the body, set while on the searchpage to make sure filters work properly. This PR removes this when moving away from the search.vue module.

small fix, to take care of the scroll problem when leaving search.

---

src/components/common/Duration.vue
src/components/records/BroadcastRecord.vue
src/components/search/SearchResults.vue
src/components/search/wc-result-item.ts
src/locales/da.json
src/locales/en.json
src/types/GenericSearchResultTypes.ts
src/utils/time-utils.ts

So, this got a little bigger than intended:
Added channel, time and duration to the search results.
Made sure we handle if nothing is there in a somewhat decent way (for now).
Moved and refactored some time util methods so they can be used by everyone.
Did some translation stuff to make sure everything, that can be, is translated.

DISC-437/add-time-on-search-results

---

tests/unit/Duration.spec.ts

I fixed the errors and adjusted them to take both locales into account as well as the new translations.
Just run the unit tests with npm run test:unit and see if the pass:)

Fix for broken duration unit tests

---

package-lock.json
package.json

This took some time but found a fix for the build error caused by Vidstack. This has triggered a new warning about unsupported TypeScript version. Hopefully I can address this issue in the package maintenance PR.
QA --> check if you can build the project.

Bump typescript to fix broken build due to vidstack

---

.eslintrc.js
src/components/global/nav/wc-header-menu.ts
src/components/search/Sort.vue
src/components/search/wc-facet-checkbox.ts
src/components/search/wc-searchbar.ts
src/views/ShowRecord.vue

First stab at fixing our crazy linter problems...
Tinkered with the eslint configuration and reintroduced the eslint-prettier integration.
It would be nice if you tried the following:
First clear node_modules and run `npm install`. You will be prompted if you try this with the wring node version.
Then:
- Mess with indention in some files and press save and see that it is fixed instantly to your liking
- Try to remove a semicolon from a line and pres save and see that it is fixed instantly to your liking
- Try to change some single quotes to double quotes press save and see that it is fixed instantly to your liking
- Try to remove a dangling (e.g. line 92 in SearchResults.vue) press save and see that it is fixed instantly to your liking
Finally try `npm run lint` and see that it runs …

First stab at eslint fix and some linting too

---

src/components/common/wc-image-item.ts
src/components/common/wc-spot-item.ts
src/components/search/wc-result-item.ts

A fairly straight forward rework.
The image now takes one property - imagedata, which we observe. If it changed, we update all the stuff. For now, we don't really have any images to show, but the placeholder shows up, and everything reacts as it should. So this will work for now untill we get a better idea of how to handle images/thumbnails/players.
Also works for both the result-item and the spot-item on the frontpage, so that's good.

DISC-760/Fix broken images

---

src/components/common/PortalContent.vue
src/components/search/CategoryTags.vue
src/components/search/Facets.vue
src/components/search/SearchOverhead.vue
src/components/search/SearchResults.vue
src/components/search/Sort.vue
src/store/searchResultStore.ts
src/views/Search.vue

There we go. Lotta refactoring, I think it's much nicer now to look at, all split up.I tried to move stuff where it belongs, and had to move the variable for showing the facets into the store, because we have several components listening for that change to make it work nicely.
Have a loot at it, and see if you think its okey - or if you find that i broke anything!

DISC-800/Refactoring of Search.vue.

---

.gitignore
package-lock.json
package.json

Added support for running lighthouse via node scripts in package.json:
- full test suite `npm run test:full` 
- seperate lighthouse test `npm run test:lh`
Added support for customising lighthouse target url via .env.local and **added default conf to configuration system (Aegis)**. Instead of this cumbersome way of modding the target url this should have been done by overriding package.json config values via arguments when calling the script. Unfortunately the support for this has been yanked pr. design --> https://github.com/npm/cli/issues/3475 
Added support for Windows environment variables

Add support for running lightouse via node scripts in package.json

---

src/components/records/BroadcastAudioRecord.vue
src/components/records/BroadcastVideoRecord.vue
src/locales/da.json
src/locales/en.json
src/views/ShowRecord.vue

So, I've added a check to see if we have a streaming URL. If we do, then we show the player. Otherwise we show a very neutral message of "we dont have the url for this".
This is just the first stab - i guess we need Design/UX to make a proper layout for this - but functionality-wise, this should be the trick.
Added for both radio and TV. Feel free to message me for 2 links, one that has an url, and one that doesn't :-) (I don't wanna share the uuids here for one of each type).

DRA-146 only loading player when the streaming url is there

---

src/api/api-client.ts
src/locales/da.json
src/locales/en.json
src/main.ts
src/store/authStore.ts
src/types/APIResponseTypes.ts
vite.config.mts

The very first POC of secure cookie flow. For now this only applies to thumbnail service. So the test is that thumbnails still work on this branch. Remember a fresh conf from Aegis.
Change log: 
Add request for auth cookie at app init
Switch to new proxy endpoint that now handles all thumbnail and authentication requests

First go at implementing secure cookie flow

---

src/components/search/ResultItem.vue

We missed a check for the mounted method of getting thumbnails from Kaltura. Since we reuse the components, sometimes coming from a video to a audio result would add a bad request for a thumbnail from kaltura. This minor fix fixes this.

DRA-bugfix: Add check for thumbnail behavior

---

src/components/search/Autocomplete.vue

I'm not quite sure why this was a bug in some way - but I've added the white background color to both the ul list and the li list elements. Now it should be *almost* impossible to have a transparent background, no matter what browser and how it decides to interpret the code.

DRA-821 - background color on autocomplete

---

src/store/searchResultStore.ts

This should make sure even if we fail, we sent an error and set the result to zero which promts the no hits page. The error needs redesign, but that's part of a larger task still at Daniels desk.

DRA-915 - spinner needs to go away after failed solr query.

---

src/components/common/CustomExpander.vue
src/components/common/PortalContent.vue
src/components/common/SimpleCheckbox.vue
src/components/common/TimeSearch/DatePicker.vue
src/components/common/TimeSearch/TimeSearchFilters.vue
src/components/common/TimeSearch/TimeSearchInitValues.ts
src/components/common/TimeSearchComponent.vue
src/components/common/TimelineHeadline.vue
src/components/global/content-elements/EdgedContentArea.vue
src/components/search/CategoryTags.vue
src/components/search/Checkbox.vue
src/components/search/Facets.vue
src/components/search/SearchOverhead.vue
src/locales/da.json
src/locales/en.json
src/store/searchResultStore.ts
src/store/timeSearchStore.ts
src/types/TimeSearchTypes.ts
src/utils/filter-utils.ts
src/views/Search.vue

Okey, this is slightly bigger than it should have been - but Daniel kept coming back with more changes. Here's the overview:
Facets have now been completely rebuild - this PR and the one before took care of this. In this PR, the following is done:
- Channel facets now has a new layout, and has no limit. So we get all of them.
- Channel facets now only change on time and search term changes. This change was requested by UX. So you can now pick several channels on a single overall query, and see them displayed. We don't change them if the query is only updated by a channel facet. This meant a lot of work and a lot of checks for what is actually requested - and a lot of the PR is just that.
- All filters in a container now has the the selected displayed next to the headline - as buttons that …

DRA-853: reworked checkbox for channels

---

src/components/common/TimeSearch/DatePicker.vue
src/components/common/TimeSearch/TimeSearchInitValues.ts
src/components/common/TimelineHeadline.vue
src/components/search/Facets.vue
src/store/timeSearchStore.ts

This PR fixes 2 things:
If no year restrictions are set when we search, the filters, when opened apply the start and end year numbers to the date pickers, so they're limited.
If you enter the site cold on a link with params set, the startTime values are not present in the filters. A new JIRA is made for the same to happen with all the other ones (month, day, timeslot, channel facets)

DRA-1198 / DRA-1197: setup min max year & filter applied

---

src/components/common/TimeSearch/TimeSearchFilters.vue

Very simple. When you use a select all in either of the time search checkboxes (months, days, timeslots), when you press the all button, it should select all, or deselect all. Before, when you deselected, the first one would always be set to true aswell. Now they all deselect, as UX want it now (as reported in DRA-1245)

DRA-1245 - deselect bug in timesearch check all button

---

src/components/global/nav/wc-header-menu.ts
src/components/search/Facets.vue
src/components/search/HitCount.vue
src/components/search/ResultItem.vue
src/components/search/SearchOverhead.vue
src/components/search/SearchResults.vue
src/components/search/Sort.vue
src/views/Search.vue

Give this a whirl, and have a look at the design on another screen (or tab between them, i know how you hate using your other screens ;-)). If you don't find any problems, we can push to develop and let Daniel have a test of it aswell. The XD file from Daniel can be found in the ticket DRA-1250, which is assigned to you aswell.
This includes
- Setup of all the overhead on the search result page
- RADIO/TV toggles placement on mobile
- Filter button placement on mobile
- XXX found placement on mobile
- page X of X placement on mobile
- grid/list placement on mobile
- sort placement on mobile
- And last but not least, the search results themselves, they've been updated a little bit, both the layout and the skeleton.

DRA-1250: Restyled resultpage to mimic the design from Daniel

---

src/components/common/TimeSearchComponent.vue
src/components/search/GridResultItem.vue
src/components/search/ResultItem.vue
src/components/search/SearchResults.vue

Super simple - they needed them to not be tied to the post, but rather just to the number in the list. Quick fix.

small fix to make them not-so-unique. Requested by testers

---

src/api/api-client.ts
src/types/APIResponseTypes.ts

Fix infinite loop triggered by consistent 401 response from bff. Fixed by implementing a retry threshhold on pending requests.

Fix infinite retry loop triggered by http 401

---

src/App.vue
src/components/global/nav/Breadcrumb.vue
src/components/global/nav/wc-header-menu.ts
src/components/records/BroadcastVideoRecord.vue
src/components/search/Header.vue
src/components/search/Hero.vue
src/components/search/HitCount.vue
src/components/search/SearchBar.vue
src/components/search/SearchOverhead.vue
src/locales/da.json
src/locales/en.json
src/router/index.ts
src/types/SearchBarTypes.ts
src/utils/test-enrichments.ts
src/views/Home.vue
src/views/Search.vue
src/views/ShowRecord.vue

Drastic rework with the following:
Hero search field removed.
Reworked menu to add kb searchfield to the header menu - added search toggle on mobile menu
Added dropdown for different portals
Added Breadcrumb for the entire application
Changed kb logo to link to kb.dk instead of application frontpage
Added a /find subpage for the search results.

DRA-809: Rework of header and searchfield and breadcrumb

---

src/assets/styles/vue-slider-styles.css
src/components/common/SkewedFoldable.vue
src/components/common/TimeSearchComponent.vue
src/components/common/timeSearch/DayPicker.vue
src/components/common/timeSearch/TimeSearchFilters.vue
src/components/common/timeSearch/TimeSearchInitValues.ts
src/components/records/BroadcastAudioRecord.vue
src/components/records/BroadcastVideoRecord.vue
src/components/search/CurrentFilters.vue
src/components/search/Facets.vue
src/components/search/NoHits.vue
src/components/search/SearchBar.vue
src/store/timeSearchStore.ts
src/types/BroadcastRecordType.ts
src/views/Search.vue

A few bugs found doing the tests (and a few i discovered myself)
- When searching from a fullpost, you now get a new set of results on the new search term.
- Doing a search from the "pick-a-date" component did not always get the filters attached to the query - this should be fixed now.
- Now picking a new month or year in the "pick-a-date" component sets the day to the first, so you don't _have_ to pick a date before doing a search.
- Fixed an error where you could get a weird breaking of the app because a response was not checked if existed before looking into the object.
- Fixed a bug where the values of the startDate and endDate were not reset when returning to the frontpage, thus messing up the timeline component's "go look at this"-link.
- Adjusted slider for new datapoints
- Minor …

DRA-optional: Bug-fixing

---

src/components/search/Autocomplete.vue

This actually fixes 3 things:
1: tabbing though did not change the search term before click - now fixed.
2: tabbing through changed the layout slightly on the elements - now fixed.
3: Added term weights (numbers) to the autocomplete - new feature.

DRA-1495: Autocomplete terms should have weights in the title

---

src/components/search/SearchBar.vue
src/store/searchResultStore.ts

Was reported by UX - search after something, apply time filters and search again. Before, it did a search on the previous searchterm instead of the new one. Fixed now.

DRA-bugfix: error when searching after timesearch.

---

src/App.vue
src/components/common/CustomTimelineSelect.vue
src/components/common/timeSearch/TimeSearchFilters.vue
src/components/global/notification/NotificationItem.vue
src/components/records/BroadcastAudioRecord.vue
src/components/records/BroadcastVideoRecord.vue
src/components/records/NotAllowedRecord.vue
src/components/search/Facets.vue
src/components/viewers/AudioVideo/VideoPlayer.vue
src/locales/da.json
src/locales/en.json
src/store/searchResultStore.ts
src/store/timeSearchStore.ts
src/views/ShowRecord.vue

- Facets are now called separately. If facets are opened when we do a new search, they're called, otherwise first when the "show filters" are opened. This gives a little loadtime, but it's fine.
- Back button now goes to the last search, wherever you might have gone, or back to the frontpage if there was no search.
- Videoplayer new respons to the 1002 error from Kaltura, throwing an error and telling the user they cant access this recording.
- Fixed a bug with filters not being applied right in the timeSearchStore.
- Fixed a few background accessibility issues.
- Removed a few console.logs

DRA-1512: facet call split out from results and more.

---

src/components/search/Facets.vue

Bugfix - category and genre selected in headline not getting loaded on a refresh on searchpage

---

src/components/common/MainCategories.vue
src/components/common/TimelineHeadline.vue
src/components/records/BroadcastAudioRecord.vue
src/components/records/BroadcastVideoRecord.vue
src/components/search/Facets.vue
src/components/search/GenreCheckbox.vue
src/locales/da.json
src/locales/en.json
src/types/TimeSearchTypes.ts
src/utils/filter-utils.ts

categories now translated in the following places:
In main categories on the frontpage.
In the facets when you open and select.
In the facet headline when you select/deselect
In the full programme post when where you can click.

Categories translated in the application

---

src/store/searchResultStore.ts

We found a place to reduce some backend calls - when the facet strings for the 2 backend facet calls are the same, we can do only one call - especially since we know this will happen anytime someone has done a new search and open the facets for the first time.

Fewer facet calls to the backend

---

src/components/common/MainCategories.vue
src/components/common/PortalContent.vue
src/components/common/SkewedFoldable.vue
src/components/search/NoHits.vue

On the frontpage, the categorys are now closed, and can be folded out, in all the layouts (before, it was open at the desktop breakpoint and forward.)
On the nohits page, the categorys are still folded out on all layouts, and the description is added. (because it's nice that way)

DRA-1532: removed the title and closed the categories container.

---

src/components/search/SearchBar.vue

We had an issue if you made a search. Then search the exact same thing with no filters or page changes. It would clear search result store. But because nothing changed it wouldn't update things in search.vue.  Made it so it does not clear or route.push if you're on the search page, and current query and last query are the same.

Bug fix search query

---

src/components/common/ImageComponent.vue

ImageData threw warnings because it was sat as type: Object as PropType<string>, but the data it got was String.
My IDE displays <img> as if it had an error. Had to change the method in style, so it wouldn't report falsely

DRA-BUGFIX imageData no longer throw warning

---

src/components/search/SearchBar.vue

Added eventlistener on click events, checks if they're part of the dropdown element, if not, then close the dropdown.

DRA-1566 dropdown close on click

---

src/components/search/Autocomplete.vue

If you hover over an autocomplete element. Then use arrows or tab to select other element. 
Before if you then clicked with your mouse, it would choose the selected element from the arrows. 
This fix should make sure, if you mouse click an element, it will always choose the clicked element. 
With enter, it should pick the active element

DRA-1478 autocomplete pick correct element

---

src/components/common/MainCategories.vue
src/components/global/content-elements/EdgedContentArea.vue
src/components/records/UnavailableRecord.vue
src/locales/da.json
src/locales/en.json
src/views/ShowRecord.vue

This should solve the problem of a manipulated record url. If you find a record and change it around to a record that doesn't exist, like http://localhost:3000/find-materiale/dr-arkivet/post/ds.tv:oai:io:fd596c49-0836-4546-b131-20ec25c6b11edsadsa - you'll now get a decent "we cant find this"-page instead of just an empty one.

DRA-1444: Handling no record ID on record page.

---

src/components/common/SimpleCheckbox.vue
src/components/search/Facets.vue

This should address the issues in 1531:
- Now the items in the channels flow down, then to the next column, as requested by UX.
- Added a hover effect that shows when you hover over them which checkbox is associated with which title - if the borders aren't enough.

DRA-1531: This should fix the issues with the column layout positioning.

---

src/components/search/NoHits.vue
src/locales/da.json
src/locales/en.json

NoHits page displays *:* in header if a user adds filters which results in no hits. 
Header now looks after *:* in query. 
Different header text
Added more space for header, to avoid word-break

DRA-BUGFIX No hit correct title

---

src/components/search/Facets.vue

we make sure, that if a new search is applied with filters, and there is nothing in the query, then we search in everything.

Small bugfix.

---

src/store/searchResultStore.ts

This ensures that if we ever get an error after an empty search, there wont be old search suggestions.

DRA-1833: empty spell suggest before new search

---

src/router/index.ts

Added a beforeEnter check to remove kalturaStartTime params on the /post/:id route to make sure we start the video from 0.
This can be checked if working on devel by entering a post, like such, with params on it:
/dr-arkivet/post/ds.tv:oai:io:633a70f4-7d3e-4962-ac1c-97e55c5c812a?KalturaStartTime=300
The route removes the params now, (in any variation of big and small letters), and starts the video at the beginning.

DRA-1867: Remove KalturaStartTime params on /post/:id route before entering.

---

src/components/search/Facets.vue
src/components/search/SearchOverhead.vue

first one makes sure we reset start=0, when we toggle tv/radio - that way we never get out of bounce.
second one was a simple change to the dates match if they're at the end of the spectrum - this way the filter is only added if it is actually set.

DRA-BUGFIX: 2 small bugfixes

---

src/components/viewers/AudioVideo/AudioPlayer.vue
src/components/viewers/AudioVideo/VideoPlayer.vue

Fixed so we always remove the picture in picture possiblity on all browsers (firefox has a builtin that showed up regardless of kalturas disabled setting)
Also fixed a small mis-alignement where an error message was missing in the audioplayer.

Bugfix: disable picture-in-picture for firefox builtin functionality

---

src/components/search/CurrentFilters.vue
src/components/search/SearchBar.vue
src/components/search/SearchOverhead.vue
src/locales/da.json
src/locales/en.json
src/router/index.ts
src/store/searchResultStore.ts
src/views/Search.vue

This PR is doing 2 things:
1: Making sure any reset of filters on *:* searches now also removes the query, sending you to an empty /find page.
2: Restyled the /find page after the UX-design provided by Daniel - which can be found in the JIRA ticket.

DRA-1882: A better /find page with no params set.

---

src/components/records/BroadcastAudioRecord.vue
src/components/records/BroadcastVideoRecord.vue
src/components/search/GridResultItem.vue

Made asked for changes to follow font settings from kb.dk
because with the line height changes to grid display. I have made the size of the card 15 px larger. 
Icons on the programme display had 10px margin to the right on kb.dk. But because we use 7px gap already, I added a 3px margin instead.

DRA-1998 font setting changes

---

src/components/search/NoHits.vue

Search by categories did not have the same style on noHits as the frontpage, when using mobile. So I have removed the padding which seemed to have fixed it.

DRA-1981 noHits search by categories

---

src/utils/datepicker-utils.ts

This should ensure that if you enter 1-1-16 (fx), it is interpreted as 1-1-2016, and thus becomes valid (the calendar component actually does that right now, our own logic did not. This should align the two)

DRA-1809: Date picker refinement.

---

src/components/records/BroadcastAudioRecord.vue
src/components/records/BroadcastVideoRecord.vue
src/components/search/SearchOverhead.vue
src/views/Search.vue

Added padding to related content title when on mobile view. 
Made it so a narrow search does not result in a 1-10 displayed, even if theres only 1 hit on the search.

Dra minor bugfixes
