.gitignore, .prettierrc.json, src/App.vue, src/api/SearchAPI.ts, src/api/search-service.ts, src/components/search/HitCount.vue, src/components/search/ImageItem.vue, src/components/search/SearchBox.vue, src/components/search/SearchResultItem.vue, src/components/search/SearchResults.vue, src/main.ts, src/router/index.ts, src/store/searchResults.ts, src/types/GenericSearchResult.ts, src/types/ServerResponses.ts, src/views/Search.vue
- Basic API call wiring
- Basic hook-up to search service
- Basic display of search result
- Basic display of thumbnail with each result
- Reworked component structure (Search split into smaller components)
=> Wok 275 setup search api call

.gitignore, src/api/search-service.ts, vue.config.js
Moved server paths to external config so vue.config.js could be published.
=> Wok 364 remove server paths from vue config

package-lock.json
Bumbed packages - this time only depth 2 or higher deps were updated
=> package audit - only updates secondary deps

src/views/Search.vue
Simple styling of the single result (and the list of results). At the moment I don't see the point in doing any more on these, before we know more about that it's gonna be like (both on the structural side, as we're waiting for the radio/TV, and on the design side)
=> Disc 3/single result webcomponent

package-lock.json, package.json, public/index.html, vue.config.js
Bump and lock to node 18.17.1 and npm 9.6.7 both versions are lts.
@jesperlauridsen - just boot the app and see that everything works as before :)
=> bump and lock to node 18.17.1 and npm 9.6.7

src/components/search/search-component.ts
=> Add missing typings and initialization to query vars

src/components/search/result-component.ts
This should fix the problem as of now - we still need to figure out a better way not to reboot the app from web components in M2.
=> should fix the problem for now

src/components/search/SearchResults.vue, src/components/search/result-component.ts, src/components/search/search-component.ts
Not really sure where this comes from. I swear it worked as intended before. This fixes it for now. Then we can change it when we have a better idea of the animation we want.
=> Weird fade in/out bug on search results

src/components/search/result-component.ts, src/types/GenericSearchResult.ts
Removes hardcoded image url and replaces with dynamic url from data response
=> Add dynamic thumb image src url

src/App.vue, src/components/nav/menu-component.ts, src/components/search/facet-checkbox-component.js, src/components/search/result-component.ts
Added a simple image load with a gradient showing untill image is ready
Added a few material icons to the search result
did some zindex cleaning and general polish
=> smooth image load, icons and css polish

src/App.vue, src/components/search/SearchResults.vue, src/components/search/result-component.ts
I think this works well (hopefully you agree!)
=> This should make it so routing is done by the app (and made optional)

src/components/search/search-component.ts, src/views/Search.vue
=> Should fix the issue with result sizes and weird scrollbars on the x-axis

src/components/nav/menu-component.ts
Now, a few notes to this PR:
I thought about making some small menu-element components, but decided against it for now because of the need for eventlisteners to click on certain elements in the menu. Bouncing events around seems unnessecary when I could achive what I wanted in the same component, without too much hassle or the component being too big.
Also, the menu rebuilds when changing - I could've made a separate function to take care of changing just translations, but that would just add more code to the file - with a minimal win (at least when I was looking it at it today)
Any feedback on this is greatly appreciated. It is, as we discussed, mainly a try to figure out how to proceed with translations in web components. So any input is nice here!
=> rebuild header with translations

src/components/search/search-component.ts
A proposal for better and safer query param handling. 
If we feel for it we can wrap the handling in a utility but I kind of think that the native API is clean enough and that we can live with the small caveats e.g. the native API handling multiple params (with same name) as an array etc.
=> Disc 91/better query update search comp

src/App.vue, src/components/notification/NotificationItem.vue, src/components/notification/NotificationManager.vue, src/components/notification/Notifier.vue, src/locales/da.json, src/locales/en.json, src/store/notificationStore.ts, src/types/Notifications.ts
This is just a draft, since it has included some buttons for test purposes. If we deem this as a good start, i'll remove the helper stuff and convert to a real pull request.
The buttons work to show what happens if several errors drop after eachother. The global error handler is now connected, so manipulating the search or fullrecord api calls now throws an error that's picked up by the notificationmanager aswell.
=> First stab at a global notifications system

src/App.vue, src/components/accordion-component.ts, src/components/nav/menu-component.ts, src/components/records/BroadcastRecord.vue, src/components/search/result-component.ts, src/components/search/search-component.ts, src/components/spot-component.ts, src/components/viewers/AudioVideo/VideoPlayer.vue, src/locales/da.json, src/locales/en.json, src/views/ShowRecord.vue
This should be a decent first stab at the full record page. I think there's only minor stuff missing, and I'll do JIRAs on that as we run along.
=> Disc 172/different header on full record

src/components/search/SearchBar.vue, src/components/search/SearchResults.vue, src/components/search/search-component.ts, src/error-handling/error-manager.ts, src/locales/da.json, src/locales/en.json, src/store/searchResults.ts, src/types/ErrorManagerType.ts, src/views/ShowRecord.vue
This started out to be a small thing but I actually had to do a bit of refactoring to get it to work.
I had to refactor SearchBar.vue to support composition API and then extend error-manager to support new error type. The rest is just implementing the stuff where error handling occurs and adding translations (I certainly hope the UX crew will give the wording an overhaul). I also took the liberty to fix the typescript error in SerchResults.vue
=> Add error handling for custom errors like malformedURI

src/components/image-component.ts, src/components/search/result-component.ts, src/components/spot-component.ts, src/main.ts, src/types/ImageComponentType.ts, src/views/Search.vue
Reworked so we have an image component that we can reuse.
=> Disc 220/image web component setup

src/utils/copy-script.ts
Revorked copy function to use clipboard API
=> Revorked copy function to use clipboard API

src/components/records/BroadcastRecord.vue, src/components/viewers/AudioVideo/video/VideoJsPlayer.vue, src/types/BroadcastRecordType.ts
Stream from wowza, and switched from hardcaded to dynamic video url taken from data.
I switched back to videoJS player because it is a cleaner solution than Kaltura (for now) when streaming from Wowza
Note - we do not differ between audio or video yet... :)
=> Stream from Wowza

src/components/search/wc-result-item.ts
This fix should remove the issue.
=> DISC-385/Firefox-cutoff

src/components/search/HitCount.vue, src/locales/da.json, src/locales/en.json, src/views/Search.vue
=> DISC-384/Made the filter button like the one in the design

src/components/search/Pager.vue, src/components/search/SearchResults.vue, src/views/Search.vue
=> small styling of the pager

src/components/records/BroadcastRecord.vue
Was a small cleanup. Not really much to do this time around, luckily.
=> DISC-414/material icons cleanup

src/App.vue, src/views/Search.vue
This adds the first stab at the tablet facets.
It's set to be active between 640px and 800px, we're still waiting for what UX deems the right breakpoints.
Bonus: A little styling for the scrollbar on webkit-devices.
=> DISC-380/tablet layout

src/components/search/Pager.vue, src/locales/da.json, src/locales/en.json
hopefully more accessability friendly. who knows tho :/?
=> DISC-415/accessability-hardening-on-pager-element

src/api/api-client.ts, src/types/APIResponseTypes.ts
I think this should do the trick?
=> Moar typing!

src/components/viewers/AudioVideo/video/VideoJsPlayer.vue, src/views/Search.vue
This adds some styling to the top on both the search page and the fullpost page. Should be enough for now - I've sent it back to the designers for review, hopefully they'll get it shaped up even better than this (on the fullpost, search should be good)
=> Disc 435/top stylng on mobile and tablet

src/components/search/Facets.vue
I only split the method up and dried it out a bit - so functionality should be EXACTLY as before:)
=> Disc 378/split update filters method

src/store/searchResultStore.ts, src/views/Search.vue
This is my best guess at how this can be done smoothly. Don't look at the first commit - that solution was brutal!
=> DISC-444/scroll to the top of the page after new search results are in.

src/components/global/nav/wc-header-menu.ts
This should fix the bug with the angled bar in the top, so it looks right in both firefox and chrome
=> DISC-449/firefox-bug

src/components/search/Facets.vue, src/components/search/SearchBarWrapper.vue, src/store/searchResultStore.ts
Now we reset start on new searches done by adding/removing filters and entering a new search phrase.
=> DISC-454/reset-start-param-on-new-searches

src/locales/da.json, src/locales/en.json, src/views/ShowRecord.vue
Small PR - user now gets 'not allowed' when encountering 403 in full record but only in the overlayed message 'toast'. We need a design for this use case for the whole full record and I already made a separate ticket for this:)
=> Change error message on 403

.eslintrc.js, src/components/global/nav/wc-header-menu.ts, src/components/search/Sort.vue, src/components/search/wc-facet-checkbox.ts, src/components/search/wc-searchbar.ts
As the title says. Fixed som small lint issues but even so I had to monkey around with the setup to get it to lint (removed prettier as extension while keeping it as plugin).
Give it a spin and see if you can lint/build.
=> Disc 577/linting issues

src/components/search/Sort.vue, src/locales/da.json, src/locales/en.json
=> fixed the right sort options and translations

src/components/viewers/AudioVideo/VideoPlayer.vue
Removed the top and bottom bars around the video, as seen here:
https://xd.adobe.com/view/f78c82ae-1e9d-4d72-ab1a-f55ae97f95c4-a2df/screen/f27cf1f5-f1bf-4e0c-8ec5-e3871d353b78/
I just out-commented them - I have a feeling we're not done with this yet.
=> removed the bars

src/App.vue
The awesome title says it all!
=> DISC-359-show-if-on-dev-or-stage-env

src/components/common/Duration.vue, src/components/search/SearchResults.vue, src/components/search/Sort.vue
Took a look at the locale handling and all in all the locale handling is implemented fine. So I:
- Trimmed some of the locale handling code in vue components
- Removed superfluous code
Going forward we need to be aware when we:
- find ourselves checking for locale in templates in Vue components (usually a ternary checking for 'da')
- find ourselves 'watching' locale in vue components - typically child components
=> Trimmed locale handling

src/App.vue, src/api/api-client.ts, src/components/records/BroadcastVideoRecord.vue, src/store/searchResultStore.ts, src/views/ShowRecord.vue
And removed the delay for morelikethis and fullpost api calls
=> Added spinner for fullpost

src/api/api-client.ts, src/components/search/SearchBarWrapper.vue, src/components/search/wc-searchbar.ts, src/store/searchResultStore.ts, src/types/APIResponseTypes.ts, vue.config.js
So, suggestions in the searchbar.
3 ways to interact with it. When you write more than 2 chars, it gets the suggestions. DR is a good test, to start with. Right now its case sensitive.
You can navigate it with the mouse, up and down keys if you have focus in the search input field, and tab, since they're made as buttons, so you can tab through them aswell. Accessability wise, there is maybe a little more work to do, but i think this is a very good starting point.
Give i a whirl and tell me what you think. I've tried to make sure it handles nice in every case. When you search it is removed, and when you search it _should_ stop the process of firing another check for suggestions after the lats keystroke.
=> Disc x/autocomplete in search bar

src/App.vue, src/components/global/nav/wc-header-menu.ts, src/components/search/CategoryTags.vue, src/components/search/wc-facet-checkbox.ts, src/components/search/wc-searchbar.ts, src/views/Search.vue
Fairly straight forward. Not anything really important here as of right now - just minor tweaks here and there.
=> Lighthouse fixes

src/api/api-client.ts, src/components/search/NoHits.vue, src/components/search/SpellChecker.vue, src/locales/da.json, src/locales/en.json, src/store/searchResultStore.ts, src/types/APIResponseTypes.ts, src/types/SpellCheckType.ts, src/views/Search.vue, tests/unit/SpellChecker.spec.ts
First Stab at spell check/did you mean function. I think we will expand this as the data gets more stable. I haven't utilised all the potentiel in the spell check data.
A few notes:
- Ignorer the out-commented part of the unit test. I couldn't get it to run due to the translation part need to be mocked and I didn't want to spend more time on it for now. The most important tests runs (check that we handle if prop is null).
- The 'lorem ipsum' in the 0-hits page is to comply with the design from UX - they want a placeholder there as there will be more text to guide the user when they get around to making a final 0-hits page design.
=> Disc 747/spell check

package-lock.json, package.json, src/components/viewers/deepzoom/DeepZoomViewer.vue, vue.config.js
Small PR but tinkered with some critical parts here:
- Updated Vue version to 3.4.19 which has **BREAKING changes**. The app seems to have survived and I basw this on the fact that the automated tests still run and I gave the app a good QA and found nothing. Please give the app a good spin to check if everything is OK - especially with regards to transitions (the vue core code changed here - hopefully to the better).
- Updated VueI18n. No problems detected but try to switch lang a few times anyway:)
- Updated some small dev. post-css package (sec. audit)  - nothing to see as it is only patch-level. Just ignore the package-lock.json diff.
- Cleaned up dev and prod dependencies so they are correct and consistent
- Removed Openseadragon from the bundle as it is not used for now.
- Had to …
=> Disc 825/maintenance 20240214

src/components/search/SearchBar.vue
A suggestion for simplifying the route logic in the search function
=> Simplify the route logic in search function

src/views/Search.vue
A suggestion for fixing the non working logic connected to error handling here using the built in error manager.
=> Refactor error handling code to use built in error manager

src/App.vue, src/components/global/nav/Footer.vue, src/components/records/BroadcastAudioRecord.vue, src/components/records/BroadcastVideoRecord.vue, src/components/search/Facets.vue, src/components/search/ResultItem.vue, src/views/About.vue, src/views/Search.vue, src/views/ShowRecord.vue
So, it worked really weird with the transitions when the footer was part of the main content, not being transitioned. So i propose that we build the footer into the different views. This makes the footer also transition in and out, which works really well. Take it for a spin, and look at the few proposed changes, and see if you're okey with this.
=> A proposed fix for the footer transition bug

src/main.ts
Kinda nothing really to see here. It works on my machine now - hopefully it works everywhere \o/
=> Should fix this.

index.html, src/components/search/Facets.vue, src/main.ts
A small fix to make the facets act right during second loading and beyond.
A small cookie script fix because that stuff keeps bugging me.
=> DRA OPTIONAL: 2 small fixes

src/components/global/notification/NotificationItem.vue
Not much to this one either, hopefully <o/
=> DRA-291 - refactored NotificationItem

.eslintrc.js, package-lock.json, package.json, src/App.vue, src/components/common/Duration.vue, src/components/common/GridDisplay.vue, src/components/global/nav/Footer.vue, src/components/global/notification/NotificationItem.vue, src/components/global/notification/Notifier.vue, src/components/records/BroadcastAudioRecord.vue, src/components/records/BroadcastVideoRecord.vue, src/components/records/GenericRecord.vue, src/components/search/Autocomplete.vue, src/components/search/CategoryTags.vue, src/components/search/Checkbox.vue, src/components/search/Facets.vue, src/components/search/HitCount.vue, src/components/search/Pager.vue, src/components/search/ResultItem.vue, src/components/search/SearchBar.vue, src/components/search/SearchResults.vue, src/components/search/Sort.vue, src/components/search/SpellChecker.vue, src/components/viewers/AudioVideo/AudioPlayer.vue, src/components/viewers/AudioVideo/VideoPlayer.vue, src/components/viewers/deepzoom/DeepZoomViewer.vue, src/i18n.ts, src/views/Search.vue, src/views/ShowRecord.vue, vite.config.mts
**Restore linting for typescript, vue and js** 
Correct setup of config for Vite 
Bumped vue eslint level from vue3-essential to vue3-reommended 
Linting of files
Patching of 'missing' GSAPTween type in notifier component
=> Restore linting for ES and TS

src/components/viewers/AudioVideo/AudioPlayer.vue, src/components/viewers/AudioVideo/VideoPlayer.vue
Pretty straight forward. Removed the tilted edges around the player.
=> removed the edges.

src/components/records/BroadcastAudioRecord.vue, src/components/viewers/AudioVideo/AudioPlayer.vue, src/types/BroadcastRecordType.ts, src/types/KalturaTypes.d.ts
Audio implementation - for now this is the same as video, so should be an easy review:)
=> Dra 249/implement kaltura audio

src/components/search/SearchResults.vue
Bug report in JIRA. this fixes it.
=> DRA-408 - error in search results.

src/components/search/SearchBar.vue
Bug report in JIRA. This fixes it.
=> DRA-409 fix to reset for the preliminary input boxes

.eslintrc.js, .prettierrc.json, index.html
Not much to it. After a few roundtrips I settled on a very simple solution.
I also tweaked a few eslint and prettier settings to remove warnings/errors in index.html that where bugging me.
You need a new conf from Aegis to test it out
=> Add application version to html source and linting

package-lock.json, package.json
Straight forward audit PR.
Things should work as before and npm audit should play nice:)
=> Audit 20240416

package-lock.json, package.json, src/components/search/Autocomplete.vue, src/dompurify.d.ts, tsconfig.json
Not much to it, but it should do the trick we won't have to worry about nasty stuff in the autocomplete
=> Dra 293/security fix for vhtml

src/api/api-client.ts, src/components/common/PortalContent.vue, src/locales/da.json, src/locales/en.json
Stright forward as title says. Remember new aegis conf
=> First stab at removing DR specifics

src/App.vue, src/components/global/nav/wc-header-menu.ts, src/components/search/Autocomplete.vue, src/components/search/CategoryTags.vue, src/components/search/SearchBar.vue, src/components/search/SpellChecker.vue, src/locales/da.json, src/locales/en.json, src/router/index.ts, src/views/Search.vue, src/views/ShowRecord.vue
This should take care of the stuff we talked about. Let me know if you find any issues (or dont like the structure!)
=> DRA-380: title logic expanded

src/App.vue, src/components/search/SearchOverhead.vue
=> DRA-461 show pages in top of search results

src/api/api-client.ts, src/store/searchResultStore.ts, src/types/APIResponseTypes.ts
=> Change to new suggester prefix - radiotv_title_suggest

src/components/search/Autocomplete.vue, src/components/search/SearchBar.vue, src/store/searchResultStore.ts
This should remove the bug with the preliminary filters not being placed correctly when re-searching after choosing one of them.
=> DRA-566/ bug in preliminary filters

src/components/search/AdditionalInfo.vue, src/components/search/ResultItem.vue, src/components/search/SoundThumbnail.vue
This is a draft until we get some feedback from design/UX. This has just been put in as a draft so we don't forget it.
=> first stab at making some generic thumbnails for audio posts.

src/components/viewers/AudioVideo/AudioPlayer.vue, src/components/viewers/AudioVideo/VideoPlayer.vue
Very small change to make partner id configurable
=> Configurable partner id

src/components/search/Facets.vue, src/components/search/ResultItem.vue, src/types/GenericSearchResultTypes.ts, src/utils/filter-utils.ts
Now much to it. Changed the creator_affiliation to _facet where it needed to. And changed the few placed we used the first element of the array to just use the generic name in creator_affiliation now.
=> DRA-834 - New creator_affiliation_facet.

src/api/api-client.ts
Removed broadcast limiter as it is no longer required.
=> Remove broadcast limiter

src/App.vue, src/components/global/nav/wc-header-menu.ts, src/components/search/Autocomplete.vue, src/components/search/CategoryTags.vue, src/components/search/SearchBar.vue, src/components/search/SpellChecker.vue, src/components/viewers/AudioVideo/AudioPlayer.vue, src/components/viewers/AudioVideo/VideoPlayer.vue, src/router/index.ts, vite.config.mts
As the title says and remember fresh conf from Aegis.
Note: streaming maybe unavailable due to backend maintenance and fallouts at cloud vendor
=> Add new base url and new confs for video and audio players

src/components/search/Autocomplete.vue, src/components/search/SearchBar.vue
=> DRA-882 - adjust text on small screens in autocomplete

src/App.vue, src/components/common/wc-image-item.ts, src/components/common/wc-spot-item.ts
Should fix weird positioning of elements on the frontpage and the font problem
=> DRA-245 - safari issues fixed

src/api/api-client.ts, src/components/common/TimeSearchComponent.vue, src/components/search/CategoryTags.vue, src/components/search/Checkbox.vue, src/components/search/Facets.vue, src/components/search/GridResultItem.vue, src/components/search/HitCount.vue, src/components/search/Pager.vue, src/components/search/SearchOverhead.vue, src/components/search/SearchResults.vue, src/components/search/Sort.vue, src/locales/da.json, src/locales/en.json, src/store/searchResultStore.ts, src/views/Search.vue
Moved facets to the top
Did some refactoring on the SearchOverhead.vue
Added a few translations
Added grid option for showing results
=> DRA-855 - facets moved to top

src/router/index.ts, src/views/404.vue
It occured to me we didn't even have the template for a 404 - so here it is!
=> Added first skeleton for 404. We didn't have  that i realized.

src/main.ts, src/store/authStore.ts
Very straight forward and small implementation until we get real OAUTH going.
Set refreshSessionBufferTime to 0 and sessionTime to 5000 or something else low to test it out. You should see a call to refresh/authenticate according to the time outs you set.
=> Add timer and refresh function for the user session

src/api/api-client.ts, vite.config.mts
New paths as we are now live with OAUTH!
=> Rewire endpoints to go through bff proxy to enforce OAUTH

src/components/records/BroadcastAudioRecord.vue, src/components/records/BroadcastVideoRecord.vue, src/components/viewers/AudioVideo/AudioPlayer.vue, src/components/viewers/AudioVideo/VideoPlayer.vue, src/utils/record-utils.ts
The title says it all - small PR. Only way to test is on devel.
=> Refactor to use entryId instead of refrenceId when streaming audio and video

src/assets/fonts/iconfont/material-icons.css, src/components/global/nav/wc-header-menu.ts, src/components/records/BroadcastAudioRecord.vue, src/components/records/BroadcastVideoRecord.vue, src/components/viewers/AudioVideo/AudioPlayer.vue, src/components/viewers/AudioVideo/VideoPlayer.vue, src/utils/record-utils.ts
Just a lot of smaller adjustments to make our header more like the kb.dk one. Lots of small tinkering.
=> Dra 804 header update

package-lock.json, package.json, src/App.vue, src/components/common/CustomExpander.vue, src/components/common/CustomTimelineSelect.vue, src/components/common/TimeSearch/TimeSearchFilters.vue, src/components/common/TimelineHeadline.vue, src/components/common/wc-image-item.ts, src/components/global/nav/wc-header-menu.ts, src/components/search/ResultItem.vue, src/locales/da.json, src/locales/en.json
Some accessability fixes here and there:
- Did a npm audit fix - removed some errors and updated the vue3-slider-component to handle some issues.
- Fixed a few issues with the slider. It now has tabindex -1 so we stick to the dropdowns if you're navigating with a keyboard.
- Reworked the checkboxes a little, to have a legend and fieldsets. A little tricky because of our structure, but my Linux screenreader is okey with this for now, as is Lighthouse. Gonna be fun to see what Monsido thinks of it.
- Found a small issue with our images and links in resultitem.
- Found a small issue in our menu - easy fix to make lighthouse happy.
=> DRA-953: Accessability fixes

src/App.vue, src/components/global/nav/wc-header-menu.ts, src/views/ShowRecord.vue
This is just a small fix to get the header more in line with the design of kb.dk when on a page that's using the cutout. Very simple not much to it. No JIRA on this, i just found it while fixing something else and decided to quickly do it too.
=> OPTIONAL: Small fix to make the top bar act appropriately

package-lock.json, package.json, src/components/search/ResultItem.vue, src/components/search/SearchOverhead.vue
Bumped required node and npm:
npm = 10.8.2
node = 20.17.0
Bumped packages:
- vue from 3.4.19 to 3.5.4
- vue-router from 4.2.5 to 4.4.4
- pinia from 2.1.7 to 2.2.2
- axios from 1.6.2 to 1.7.7
Fix bug in error message when deselecting both radio and tv 'radio buttons' in search result
Remove console.log in ResultItem.vue
=> Maintenance package 2024-09-11

index.html
So, this is the first stab at a small seo optimization of the application. I am no expert on this field, but as far as I can tell, this should be a decent start for us. Feel free to give me any suggestions as to how we could further improve it!
=> DRA-16 -  Google seo optimization

src/App.vue, src/api/api-client.ts, src/components/viewers/AudioVideo/AudioPlayer.vue, src/components/viewers/AudioVideo/VideoPlayer.vue, src/store/authStore.ts, src/types/APIResponseTypes.ts
Small PR,
Requesting data from the bff backend and saving them nicely for when the player needs to be loaded and mounted.
=> DRA-553: Fetch of kaltura conf from backend on mount

src/components/search/Facets.vue, src/components/search/SearchOverhead.vue
=> Should fix the bug with reset on filters

src/components/common/GridDisplay.vue
We needed touchevents to make the content in the draggable containers work nicely.
=> this should take care of the non-responsiveness on mobile

src/assets/images/404.svg, src/locales/da.json, src/locales/en.json, src/views/404.vue
404 page when url doesn't exists.
contains kb 404 image. Buttons for the frontpage of dr-archive and kb.dk
Displays content differently when page gets smaller.
test id for link buttons
=> Dra 881 implement 404 page

src/components/common/CustomExpander.vue, src/components/common/TimeSearchComponent.vue, src/components/common/TimelineHeadline.vue, src/components/common/timeSearch/TimeSearchFilters.vue, src/components/global/content-elements/EdgedContentArea.vue, src/components/search/Facets.vue, src/components/search/ItemSlider.vue, src/locales/da.json, src/locales/en.json, src/views/Search.vue
This adds a full-width background to the time filters when opened.
Minor tweaks in a few other places to make sure this doesn't break anything on the frontpage either
=> DRA-1380: Fullwidth background on the time facets

src/api/api-client.ts, src/components/common/GridDisplay.vue, src/components/common/PortalContent.vue, src/components/search/CurrentFilters.vue, src/components/search/GridResultItem.vue, src/components/search/Header.vue, src/components/search/SearchResults.vue, src/store/searchResultStore.ts
Fixed so there is some rotational content.
This is just the first stab to get real data in. More work is needed later to get a full list when it's ready.
=> Dra 1430 first stab at rotatable content

src/components/common/PortalContent.vue, src/components/common/SkewedFoldable.vue
Reworked the daypicker a little bit:*
Now has a hover on the entire element.
Now shows the fold out button on all layouts
Reworked, so the fold out button now has the same look as the other ones on the desktop layout.
=> DRA-1469: reworked hover on day-picker on frontpage

src/components/search/Sort.vue
sort arrows. can flip between asc and desc. defaults to desc for each "category"
=> Dra 1258 result sorting

src/components/search/SearchOverhead.vue
Made the filter buttons larger (show, reset, tv, radio)
=> show and reset buttons larger. tv and radio button larger

src/components/records/BroadcastAudioRecord.vue, src/components/records/BroadcastVideoRecord.vue
Return button on record. Styling changed. It needed to be more visible. So its larger, and further up (follows description text)
=> Dra 1470 return button

index.html
Hopefully pretty simple. This works on my machine, and hopefully does the same on devel/stage/prod when we get there too.
=> DRA-1471 - cookie script path changed.

src/components/common/MainCategories.vue
=> Category styling

src/components/search/GridResultItem.vue, src/components/search/ResultItem.vue, src/components/search/SoundThumbnail.vue
Added title to image. Made alt more unique
=> Soundthumbnail changes after accessibility report 

src/assets/styles/vue-slider-styles.css, src/components/common/CustomExpander.vue, src/components/common/GridDisplay.vue, src/components/common/MainCategories.vue, src/components/common/SkewedFoldable.vue, src/components/common/timeSearch/TimeSearchFilters.vue, src/components/global/notification/NotificationItem.vue, src/components/search/SearchBar.vue
This fixes a few accessability issues, and a FF bug o/ (ty for finding it, Patrick!)
=> Accessability and FF fix

src/components/common/timeSearch/DatePicker.vue, src/components/common/timeSearch/DayPicker.vue, src/components/global/content-elements/NotAllowedBanner.vue, src/components/search/AdditionalInfo.vue, src/components/search/CurrentFilters.vue, src/components/search/GridResultItem.vue, src/components/search/NoHits.vue, src/components/search/ResultItem.vue, src/locales/da.json, src/locales/en.json, src/store/searchResultStore.ts, src/store/timeSearchStore.ts, src/views/ShowRecord.vue
Added localization where needed. Made some custom error pop-ups.
=> English translations.

src/views/Search.vue
=> Search param fix for customError

src/App.vue, src/types/APIResponseTypes.ts
if alert1 got data, submit error.
=> Messages pop-up

src/App.vue, src/components/common/PortalContent.vue, src/locales/da.json, src/locales/en.json
Added an alert if slow response.
=> Slow response alert

src/components/common/MainCategories.vue
Changed notify event to use submitCustomError
=> Main categories custom error

index.html
This should add the tracking scripts that UX wants.
=> DRA-1497 - tracking scripts added

src/components/search/SearchOverhead.vue
better reset button functionality. Now it's the same in both CurrentFilters and SearchOverhead. Good catch.
=> better reset button

src/locales/da.json, src/locales/en.json, src/views/404.vue, src/views/Search.vue
Added about button
added contact button
Changed spacing
=> Dra 1424 404 update

src/components/global/content-elements/EdgedContentArea.vue, src/components/search/Facets.vue, src/components/search/GridResultItem.vue
This should fix the 4 styling errors mentioned in the 4 tickets on JIRA.
=> DRA-1525-1525-1526-1527-mobile styling on facets container

src/components/search/HitCount.vue, src/locales/da.json, src/locales/en.json
The issue is described in DRA-1554. Very straight forward change.
=> DRA-1554: new headline text on filter searches.

src/components/global/nav/Breadcrumb.vue
=> DRA-1529 - hide breadcrumb nicely

src/components/records/BroadcastAudioRecord.vue, src/components/records/BroadcastVideoRecord.vue, src/components/search/ContactUs.vue, src/components/search/NoHits.vue, src/views/404.vue
Added the ask the library button on the needed areas.
Made it its own component for reuse.
=> Dra 1528 ask library

src/components/search/Pager.vue, src/locales/da.json, src/locales/en.json, src/views/Search.vue
On the search page - added an input for a page number.
Now scrolls to the top of window when changing a page
Pager now only displays 5 pages on less than 850px in width. 10 pages when above.
=> Dra write page number

src/components/search/Hero.vue
This should fix it. Seems to work on mac now. And I don't see any issues on other browsers
=> Added alternate-reverse to animation

src/components/common/timeSearch/TimeSearchFilters.vue, src/components/global/content-elements/EdgedContentArea.vue, src/components/search/Facets.vue, src/components/search/Header.vue, src/components/search/SearchOverhead.vue, src/components/viewers/AudioVideo/AudioPlayer.vue, src/components/viewers/AudioVideo/VideoPlayer.vue, src/views/ShowRecord.vue
Made extra hide filters button.
EdgeContentArea now same as frontpage on 4k monitor. Where we smooth out the skewed lined.
The videoplayer became slightly hidden behind breadcrumb on 4k.
=> Dra 1647 extra close filters

src/components/common/PortalContent.vue
In order to test if the through time segment is visible.
=> Added testid

src/components/common/InfoComponent.vue, src/components/global/nav/Breadcrumb.vue
I found a small bug in the breadcrumb on smaller screen when playing around with it. This should make sure it behaves somewhat properly.
=> FIX: Issues with the breadcrumb on mobile

src/components/search/SearchBar.vue
Very simple, just need some test-ids here :-)
=> Added some test-ids to the portal dropdown

src/components/search/Pager.vue, src/components/search/SearchOverhead.vue, src/components/search/Sort.vue, src/locales/da.json, src/locales/en.json, src/store/searchResultStore.ts, src/views/Search.vue
We wish to display, how many results are in the current page, and what that amounts to out of the total result count.
Added pageNumber to store, because I wished to reuse it, and it just became convoluted math in the html.
=> Display total results and sort icon

src/locales/da.json, src/locales/en.json
=> DRA-1837: simple text change

src/components/common/MainCategories.vue, src/components/common/SkewedFoldable.vue, src/components/common/TimeSearchComponent.vue
some h1's changed to a more fitting h2.
=> DR-1809 rewrite some h1s to h2.

src/locales/da.json, src/locales/en.json, src/views/Search.vue
So, this is a rework of how we set the title at the Search page. There is now a function, looking at what params the search was based on. If there was a q, we use that. If not, we look at the different filters and find out exactly how we want the title to look.
Have a look through and test it, and see if it holds up.
=> DRA-1484: new title setup

src/components/common/TimelineHeadline.vue, src/components/search/Facets.vue
Just a change of icon and a small adding of margin. Nothing big.
=> DRA-1666: Simple change of icon

src/components/common/CustomExpander.vue, src/components/common/TimelineHeadline.vue
Selected channels now create an overflow button.
Overflow button displays the amount of selected channels, that are not shown in the overview.
Eventlistener on the size of the window, to make sure the design is dynamic.
=> DRA-OPTIONAL channel selection cleaner design

src/components/records/BroadcastAudioRecord.vue, src/components/records/BroadcastVideoRecord.vue, src/components/search/GridResultItem.vue, src/components/search/ResultItem.vue, src/locales/da.json, src/locales/en.json, src/types/BroadcastRecordType.ts, src/types/GenericSearchResultTypes.ts
Added episode number for record display and search records. 
It only display if a record has it in the metadata.
=> Dra 2012 add episode number

src/components/global/nav/Footer.vue
I only saw that we had an issue with this with the footer. Followed the padding used on kb.dk
=> DRA-2003 need distance between the borders of the browser

src/components/common/TimelineHeadline.vue, src/components/search/Facets.vue
Design asked for more distance between channel checkboxes and the labels for selected channels. 
Also asked for more distance between the labels, when using tablet or below. 
Color change for x+ label, to make sure the functionality seem different than the other labels.
=> Color change and more distance

src/components/search/GridResultItem.vue
Added missing padding. Added hidden div, to keep size
=> Grid item fix sizing between items with or without episodes
